<?xml version="1.0"?>
<robot name="exr1" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="wheel_separation" value="0.6" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="body_height" value="0.01" />

  <xacro:include filename="$(find exr1_description)/urdf/utils.xacro" />
  <xacro:include filename="$(find exr1_description)/urdf/wheel.urdf.xacro" />

  <link name="base_footprint" />

  <joint name="body_joint" type="fixed">
    <parent link="base_link" />
    <child link="body_link" />
    <origin xyz="0 0 ${0.2 + body_height}" rpy="0 0 0" />
  </joint>
  <link name="body_link">
    <xacro:inertial_box mass="28" x="0.7" y="0.7" z="0.4">
      <origin xyz="0 0 0" />
    </xacro:inertial_box>
    <collision>
      <geometry>
        <box size="0.7 0.7 0.4" />
      </geometry>
    </collision>
    <visual>
      <geometry>
        <box size="0.7 0.7 0.4" />
      </geometry>
    </visual>
  </link>

  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>
  <link name="base_link" />

  <xacro:wheel name="front_left">
    <origin xyz="${wheel_separation} ${wheel_separation} ${wheel_radius}"
      rpy="${-pi/2} 0 ${1*pi/4+pi/2}" />
  </xacro:wheel>

  <xacro:wheel name="rear_left">
    <origin xyz="${-wheel_separation} ${wheel_separation} ${wheel_radius}"
      rpy="${-pi/2} 0 ${3*pi/4+pi/2}" />
  </xacro:wheel>

  <xacro:wheel name="rear_right">
    <origin xyz="${-wheel_separation} ${-wheel_separation} ${wheel_radius}"
      rpy="${-pi/2} 0 ${5*pi/4+pi/2}" />
  </xacro:wheel>

  <xacro:wheel name="front_right">
    <origin xyz="${wheel_separation} ${-wheel_separation} ${wheel_radius}"
      rpy="${-pi/2} 0 ${7*pi/4+pi/2}" />
  </xacro:wheel>

  <gazebo>
    <plugin filename="libexr1_sim_plugin.so" name="exr1_gz::Exr1System">
      <!-- <wheel0_joint>front_left_wheel_joint</wheel0_joint> -->
      <!-- <wheel1_joint>rear_left_wheel_joint</wheel1_joint> -->
      <!-- <wheel2_joint>rear_right_wheel_joint</wheel2_joint> -->
      <!-- <wheel3_joint>front_right_wheel_joint</wheel3_joint> -->
      <max_wheel_torque>10.0</max_wheel_torque>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <linear_damping>50</linear_damping>
      <angular_damping>5</angular_damping>
      <base_link>base_footprint</base_link>
      <!-- <mass>30</mass> -->
      <!-- <center_of_mass>${-wheel_separation/2.0*(1.0-cos(pi/3))} 0</center_of_mass> -->
      <!-- <center_of_mass>0 0</center_of_mass> -->
      <!-- <moment_of_inertia>2.29</moment_of_inertia> -->
      <!-- <linear_kp>1</linear_kp> -->
      <!-- <linear_ki>0</linear_ki> -->
      <!-- <linear_kd>0</linear_kd> -->
      <!-- <angular_kp>0</angular_kp> -->
      <!-- <angular_ki>0</angular_ki> -->
      <!-- <angular_kd>0</angular_kd> -->
    </plugin>
  </gazebo>
</robot>
