<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" xmlns:gz="http://gazebosim.org/schema">
  <xacro:macro name="ld06_lidar" params="name topic parent_link:=base_link *origin">
    <xacro:property name="joint_name" value="${name}_joint" />
    <xacro:property name="link_name" value="${name}_link" />
    <xacro:property name="width" value="0.03859" />
    <xacro:property name="height" value="0.03330" />
    <xacro:property name="mass" value="0.042" />
    <xacro:property name="z_offset" value="${-(height/2 - 0.0076)}" />

    <joint name="${joint_name}" type="fixed">
      <parent link="${parent_link}" />
      <child link="${link_name}" />
      <xacro:insert_block name="origin" />
    </joint>

    <link name="${link_name}">
      <visual>
        <origin xyz="0 0 ${z_offset}" />
        <geometry>
          <box size="${width} ${width} ${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${z_offset}" />
        <geometry>
          <box size="${width} ${width} ${height}" />
        </geometry>
      </collision>
      <xacro:inertial_box mass="${mass}" x="${width}" y="${width}" z="${height}">
        <origin xyz="0 0 ${z_offset}" />
      </xacro:inertial_box>
    </link>

    <gazebo reference="${link_name}">
      <sensor name="${name}" type="gpu_lidar">
        <gz_frame_id>${link_name}</gz_frame_id>
        <topic>${topic}</topic>
        <update_rate>10</update_rate>
        <lidar>
          <scan>
            <horizontal>
              <samples>450</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>${2*pi}</max_angle>
            </horizontal>
            <vertical>
              <samples>1</samples>
              <resolution>0.1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </vertical>
          </scan>
          <range>
            <min>0.02</min>
            <max>12</max>
            <resolution>0.015</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </lidar>
        <always_on>1</always_on>
        <visualize>true</visualize>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>
