<?xml version="1.0"?>
<robot name="field" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="field_width" value="8.0" />
  <xacro:property name="field_height" value="3.0" />
  <xacro:property name="fence_height" value="0.15" />
  <xacro:property name="fence_width" value="0.15" />

  <xacro:macro name="fence" params="name xy length yaw_deg">
    <link name="${name}_link">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <visual>
        <geometry>
          <box size="${length} ${fence_width} ${fence_height}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${length} ${fence_width} ${fence_height}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="1" />
        <origin xyz="${xy} 0" rpy="0 0 ${radians(yaw_deg)}" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>
    </link>
    <joint name="${name}_joint" type="fixed">
      <parent link="root" />
      <child link="${name}_link" />
      <origin xyz="${xy} ${fence_height/2}" rpy="0 0 ${radians(yaw_deg)}" />
    </joint>
  </xacro:macro>

  <link name="root" />

  <xacro:fence name="north_fence" xy="0 ${field_height+fence_width/2}" length="${field_width}"
    yaw_deg="0" />
  <xacro:fence name="south_fence" xy="0 ${-fence_width/2}" length="${field_width}" yaw_deg="0" />
  <xacro:fence name="east_fence" xy="${field_width/2+fence_width/2} ${field_height/2}"
    length="${field_height+fence_width*2}"
    yaw_deg="90" />
  <xacro:fence name="west_fence"
    xy="${-field_width/2-fence_width/2} ${field_height/2}"
    length="${field_height+fence_width*2}"
    yaw_deg="90" />

  <gazebo>
    <static>true</static>
  </gazebo>
</robot>
